version: '3.3'

services:
  db:
    image: postgres:16-alpine
    container_name: garant-beton-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: garant_beton
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD:-DMpydJOsv3NYt8Ef0eX6NR4=}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=ru_RU.UTF-8 --lc-ctype=ru_RU.UTF-8"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - garant-beton-network
    healthcheck:
      test: pg_isready -U postgres
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: garant-beton-backend
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://postgres:${DB_PASSWORD:-DMpydJOsv3NYt8Ef0eX6NR4=}@db:5432/garant_beton
      JWT_SECRET: ${JWT_SECRET:-garant-beton-super-secret-jwt-key-2025-production-min-32-chars}
      NODE_ENV: production
      PORT: 4000
      CORS_ORIGIN: ${CORS_ORIGIN:-https://gar-ant-bet-on.ru,http://gar-ant-bet-on.ru,https://www.gar-ant-bet-on.ru,http://www.gar-ant-bet-on.ru,http://78.40.109.177}
      ORS_API_KEY: ${ORS_API_KEY}
    ports:
      - "4000:4000"
    depends_on:
      - db
    networks:
      - garant-beton-network
    volumes:
      - ./backend/prisma:/app/backend/prisma:ro
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:4000/api/v1/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx:alpine
    container_name: garant-beton-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/dist:/usr/share/nginx/html:ro
    depends_on:
      - backend
    networks:
      - garant-beton-network

volumes:
  postgres_data:
    driver: local

networks:
  garant-beton-network:
    driver: bridge
