services:
  # Backend Service
  - type: web
    name: garant-beton-backend
    runtime: node
    region: frankfurt
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: CORS_ORIGIN
        value: https://garant-beton-frontend.onrender.com
    healthCheckPath: /api/v1/health

  # Frontend Service  
  - type: web
    name: garant-beton-frontend
    runtime: static
    region: frankfurt
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://garant-beton-backend.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  # Database (PostgreSQL)
databases:
  - name: garant-beton-db
    databaseName: garant_beton
    region: frankfurt
    plan: free
    ipAllowList: []

