services:
  # Backend Service
  - type: web
    name: garant-beton-backend
    runtime: node
    region: frankfurt
    plan: free
    rootDirectory: backend
    buildCommand: npm install && npx prisma generate && npx prisma migrate deploy && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: garant-beton-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: CORS_ORIGIN
        value: https://garant-beton-frontend.onrender.com
      - key: ORS_API_KEY
        sync: false
    healthCheckPath: /api/v1/health

  # Frontend Service  
  - type: web
    name: garant-beton-frontend
    runtime: static
    region: frankfurt
    plan: free
    rootDirectory: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://garant-beton-backend.onrender.com/api/v1
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  # Database (PostgreSQL)
databases:
  - name: garant-beton-db
    databaseName: garant_beton
    region: frankfurt
    plan: free
    ipAllowList: []

